### ISSUE TITLE
Model for internal Dr.

### ISSUE THREAD

**Issue by vincentdavis** [Heteroskedastic/Dr-referral-tracker#15] opened 2016-02-19 03:42 UTC
All patients are seen by a Dr. (Actually they may not be a doctor)
Need a model for internal doctors
every patient visit is related to 1 Dr.

**Comment by pedro-walter** [comment] 2016-03-10 05:35
Class Doctor was created, so far I only added the doctor name as a field, do we need any other ones?

**Comment by vincentdavis** [comment] 2016-03-10 13:38
I can see that we will soon what one more field in the Doctor model.
"level" with defined choices (PA, Dr)
FYI
PA is Physician Assistant,
Dr. obviously Doctor.
All patients are seen (treated) by a PA or a Dr and we may in the future want a report for just the PA's

**Comment by pedro-walter** [comment] 2016-03-10 16:07
Then I believe the name Doctor is not adequate. The problem is that the names Practitioner and Physician were used before for other classes and might confuse the customer. Maybe something like Staff or Medic or Employee. Instead of "level", I believe "rank" or "position" is a better term.

**Comment by pedro-walter** [comment] 2016-03-13 22:12
Resolved by commit https://github.com/Heteroskedastic/Dr-referral-tracker/commit/d4da930e56290c0fc6ac7a0fb2edf99a5ec5aa26

**Closed by pedro-walter** 2016-03-13 22:12 UTC
Labels: enhancement, Medium Priority
